version: "1.0"
info:
  model: int-scaffold
packages:
- name: May23ProjectProject
  gitServerName: NewExtgit
  gitUrl: https://github.com/Kruthika-K-IBM
  gitUsername: Kruthika-K-IBM
  gitBranch: main
